### ISSUE TITLE
regression: query error with case when as the group field

### ISSUE THREAD

**Issue by haohuaijin** [apache/datafusion#11118] opened 2024-06-25 06:20 UTC
### Describe the bug

```
Internal error: Input field name CASE WHEN concat(t.b, Utf8("hello")) = Utf8("test") THEN Utf8("good") ELSE Utf8("bad") END does not match with the projection expression CASE WHEN concat(t.b,Utf8("hello")) = Utf8("test") THEN Utf8("good") ELSE Utf8("bad") END.
This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker
```

### To Reproduce

```
DataFusion CLI v39.0.0
> create table t(a int, b text);
0 row(s) fetched.
Elapsed 0.019 seconds.

> insert into t values (1,'hello'), (2,'world');
+-------+
| count |
+-------+
| 2     |
+-------+
1 row(s) fetched.
Elapsed 0.019 seconds.

> select (case when concat(b, 'hello') = 'test' THEN 'good' else 'bad' END) as c from t group by c;
Internal error: Input field name CASE WHEN concat(t.b, Utf8("hello")) = Utf8("test") THEN Utf8("good") ELSE Utf8("bad") END does not match with the projection expression CASE WHEN concat(t.b,Utf8("hello")) = Utf8("test") THEN Utf8("good") ELSE Utf8("bad") END.
This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker
```

### Expected behavior

run success

### Additional context

I also check in v37 and v38

v37 can run, but v38 report error
```
DataFusion CLI v37.0.0
❯ create table t(a int, b text);
insert into t values (1,'hello'), (2,'world');
select (case when concat(b, 'hello') = 'test' THEN 'good' else 'bad' END) as c from t group by c;
0 rows in set. Query took 0.006 seconds.

+-------+
| count |
+-------+
| 2     |
+-------+
1 row in set. Query took 0.014 seconds.

+-----+
| c   |
+-----+
| bad |
+-----+
1 row in set. Query took 0.020 seconds.
```
```
DataFusion CLI v38.0.0
> create table t(a int, b text);
insert into t values (1,'hello'), (2,'world');
select (case when concat(b, 'hello') = 'test' THEN 'good' else 'bad' END) as c from t group by c;
0 row(s) fetched.
Elapsed 0.008 seconds.

+-------+
| count |
+-------+
| 2     |
+-------+
1 row(s) fetched.
Elapsed 0.007 seconds.

Internal error: Input field name CASE WHEN concat(t.b, Utf8("hello")) = Utf8("test") THEN Utf8("good") ELSE Utf8("bad") END does not match with the projection expression CASE WHEN concat(t.b,Utf8("hello")) = Utf8("test") THEN Utf8("good") ELSE Utf8("bad") END.
This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker
```

**Comment by doki23** [comment] 2024-06-25 07:01
It seems that the projection expression lacks a whitespace between `t.b` and `Utf8("hello")`.

**Comment by jonahgao** [comment] 2024-06-25 15:37
It might be related to #10088, and could be due to the gap between `physical_name` and `Expr::display_name` of case expressions.

**Comment by jcsherin** [comment] 2024-06-26 15:03
> It might be related to #10088, and could be due to the gap between `physical_name` and `Expr::display_name` of case expressions.

The error originates from the following check between input field names and projection expressions. It seems like failure is the expected behavior. Before v38 the mismatch was being silently ignored. But now they are being detected.

https://github.com/apache/datafusion/blob/b21bf9e8527de82e901c3a61127d63779f230163/datafusion/physical-expr/src/equivalence/projection.rs#L70-L73

The use of any scalar function inside `case` will fail similarly. An example,
```SQL
select (case when ends_with(b, 'hello') THEN 'good' else 'bad' END) as c from t group by c;

Internal error: Input field name 
CASE WHEN ends_with(t.b, Utf8("hello")) THEN Utf8("good") ELSE Utf8("bad") END 
does not match with the projection expression 
CASE WHEN ends_with(t.b,Utf8("hello")) THEN Utf8("good") ELSE Utf8("bad") END.
```
There exists a formatting mismatch in implementations,

1. The default implementation of `display_name` does not put a space after the separator like: `.join(", ")`.
https://github.com/apache/datafusion/blob/82f7bf40adb742fc566ce8b280afa344cc85107c/datafusion/expr/src/udf.rs#L339

2. But the `fmt::Display` for `Expr::ScalarFunction` puts a space after the separator:
https://github.com/apache/datafusion/blob/82f7bf40adb742fc566ce8b280afa344cc85107c/datafusion/expr/src/expr.rs#L1904

This is [a recent issue which reports the same bug and proposes to fix it by standardizing the separator](#10364) in `display_name`. Even though the actual fix is small, many cascading changes are required in existing test snapshots.

**Comment by jonahgao** [comment] 2024-06-26 15:28
A failed query that does not involve separators.
```sh
> create table t(a int, b text);
0 row(s) fetched.
Elapsed 0.005 seconds.

> select (case a::bigint when 1 THEN 1 END) as c from t group by c;
Internal error: Input field name CASE CAST(t.a AS Int64) WHEN Int64(1) THEN Int64(1) END does not match with the projection expression CASE t.a WHEN Int64(1) THEN Int64(1) END.
This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker
```

I think having multiple different types of names for expressions, while also ensuring they are the same, seems somewhat burdensome and error-prone.🤔

**Comment by alamb** [comment] 2024-06-26 17:43
I think this Issue is resolved in https://github.com/apache/datafusion/pull/11133 by @jonahgao 

However I am not sure if @jonahgao  plans additional changes before we should close this issue -- or if perhaps we should file a new ticket

**Comment by jonahgao** [comment] 2024-06-27 01:35
Let's close it for this case. I'll open a new issue if there are new findings.

**Closed by jonahgao** 2024-06-27 01:35 UTC
Labels: bug
