### ISSUE TITLE
`generate_series` hangs indefinitely when providing a step of less than 1 day

### ISSUE THREAD

**Issue by Abdullahsab3** [apache/datafusion#11823] opened 2024-08-05 11:53 UTC
### Describe the bug

When using dates for `generate_series` and providing a step of less than 1 day, Datafusion hangs indefinitely without any failures/successes (or maybe I didn't wait long enough :-) )

### To Reproduce

```
select generate_series(date '2023-01-01', date '2023-02-01', interval '1 hour');
```

### Expected behavior

Return the grouping, or an error to indicate it may not be implemented/expected

**Comment by tshauck** [comment] 2024-08-06 04:10
I took a quick look here, and I think the root cause may be in arrow.

For one, the generate series uses a Date32, I tried to change it to a date64, but then ran into what I think is an issue with adding `IntervalMonthDayNanoType` to a date. See https://github.com/apache/arrow-rs/issues/6198 for more info.

**Comment by alamb** [comment] 2024-08-09 18:30
@tshauck  has a PR up that fixes this ❤️  --  https://github.com/apache/datafusion/pull/11907. I expect it will be merged shortly

**Closed** 2024-08-11 14:11 UTC
Labels: bug
