### ISSUE TITLE
Eliminate filter when `pushdown_filters`  is enabled

### ISSUE THREAD

**Issue by Dandandan** [apache/datafusion#7688] opened 2023-09-28 20:51 UTC
### Is your feature request related to a problem or challenge?

When `pushdown_filters` is enabled, DF should be able to eliminate the subsequent filter.
When enabling the option for tpc-h benchmark, the `FilterExec` and `l_shipdate` projection is still present in the plans.

For example query 3 we can see the filter:

```
FilterExec: l_shipdate@3 > 9204
  ParquetExec: file_groups={2 groups: [[...]]},
    projection=[l_orderkey, l_extendedprice, l_discount, l_shipdate], predicate=l_shipdate@10 > 9204, pruning_predicate=l_shipdate_max@0 > 9204
```

### Describe the solution you'd like

Remove the filter when.

We probably need to make some changes to `TableProvider` `FileFormat` to support removing the filter based on the file format.

**Comment by alamb** [comment] 2024-09-18 15:08
I believe this is a duplicate of https://github.com/apache/datafusion/issues/4028, which  @itsjunetime  completed  in https://github.com/apache/datafusion/pull/12135

Tests are here https://github.com/apache/datafusion/blob/main/datafusion/sqllogictest/test_files/parquet_filter_pushdown.slt

Let me know if I got that incorrect

**Closed by alamb** 2024-09-18 15:08 UTC
Labels: enhancement, performance
