### ISSUE TITLE
`ProjectionPushDown` creates invalid `Aggregate` plans

### ISSUE THREAD

**Issue by andygrove** [apache/datafusion#3285] opened 2022-08-29 16:39 UTC
**Describe the bug**
`ProjectionPushDown` creates invalid `Aggregate` plans where the schema does not match the grouping and aggregate expressions.

**To Reproduce**
PR coming up with validation to catch this.

**Expected behavior**
Schema should have one field per grouping and aggregate expression.

**Additional context**
None

**Comment by eejbyfeldt** [comment] 2024-10-30 08:16
@andygrove Should we close this? Since it over 2 years old and does not have a reproducer?

**Comment by alamb** [comment] 2024-11-02 20:15
Thanks for flagging this @eejbyfeldt

**Closed** 2024-11-02 20:15 UTC
Labels: bug
