### ISSUE TITLE
Move `sql_compound_identifier_to_expr` to `ExprPlanner`

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#11473] opened 2024-07-15 16:57 UTC
### Is your feature request related to a problem or challenge?

Part of https://github.com/apache/datafusion/issues/11207

As discussed in https://github.com/apache/datafusion/issues/11207 The idea is to move hardcoded the `sql_compound_identifier_to_expr `  operator to function in the parser step, which is currently handled in the optimizer step. We need to implement user-defined parser mechanisms to enable more flexible SQL planning.

### Describe alternatives you've considered

I think you can just follow the model of https://github.com/apache/datafusion/pull/11398 and add a function to `ExprPlanner` and then update the sql planner to call it instead of `get_functon_meta`

**Comment by dharanad** [comment] 2024-07-15 17:03
seems like a duplicate of https://github.com/apache/datafusion/issues/11244
i will close and we can keep this open

**Comment by dharanad** [comment] 2024-07-15 17:03
take

**Comment by alamb** [comment] 2024-07-15 18:08
Sorry @dharanad  -- I didn't see https://github.com/apache/datafusion/issues/11244 before

**Comment by dharanad** [comment] 2024-07-16 03:43
> Sorry @dharanad -- I didn't see #11244 before

No worries at all.

**Comment by dharanad** [comment] 2024-07-16 06:40
QQ: @alamb In `sql_compound_identifier_to_expr` the only this which is using `get_function_meta` is `get_field` ScalarUDF. I think ideally we should move `get_field` to `ExprPlanner`. Rest of code as dependecy on `SqlToRel` struct

**Comment by alamb** [comment] 2024-07-16 21:48
> I think ideally we should move get_field to ExprPlanner. Rest of code as dependecy on SqlToRel struct



Makes sense to me 👍

**Comment by alamb** [comment] 2024-07-21 12:33
After https://github.com/apache/datafusion/pull/11487 I wonder if there is anythng left for this item?

**Comment by jayzhan211** [comment] 2024-07-22 01:21
I think we are done with this item

**Closed by jayzhan211** 2024-07-22 01:21 UTC
