### ISSUE TITLE
`Unnest` query does not allow one expression being referenced multiple times

### ISSUE THREAD

**Issue by duongcongtoai** [apache/datafusion#11198] opened 2024-07-01 18:44 UTC
### Describe the bug

Given this slt

```
statement ok
CREATE TABLE unnest_table
AS VALUES
    ([1,2,3])
;

select unnest(column1), unnest(column1) + 1 from unnest_table;
```

Datafusion throws error
```
External error: query failed: DataFusion error: Error during planning: Projections require unique expression names but the expression "unnest_table.column1 AS unnest(unnest_table.column1)" at position 0 and "unnest_table.column1 AS unnest(unnest_table.column1)" at position 1 have the same name. Consider aliasing ("AS") one of them.
```

### Expected behavior

unnest(expr) can be referenced multiple times within select statement

**Comment by jonahgao** [comment] 2024-07-02 14:28
This should be a duplicate of #6543

**Comment by duongcongtoai** [comment] 2024-07-15 20:26
Although theoretically #6543 can solve this ticket, but i think the bug presented here comes from the internal implementation inside try_process_unnest function itself, and can be fixed within this function
```
CREATE TABLE unnest_table
AS VALUES
    ([1,2,3]);

query TT
explain select unnest(column1), unnest(column1) + 1 from unnest_table;
----
Current plan generated (which causes error)
logical_plan
01)Projection: unnest(unnest_table.column1), unnest(unnest_table.column1) + Int64(1)
02)--Unnest: lists[unnest(unnest_table.column1)] structs[]
03)----Projection: unnest_table.column1 AS unnest(unnest_table.column1), unnest_table.column1 AS unnest(unnest_table.column1)
04)------TableScan: unnest_table projection=[column1]

Better plan generated
logical_plan
01)Projection: unnest(unnest_table.column1), unnest(unnest_table.column1) + Int64(1)
02)--Unnest: lists[unnest(unnest_table.column1)] structs[]
03)----Projection: unnest_table.column1 AS unnest(unnest_table.column1)
04)------TableScan: unnest_table projection=[column1]
```

We also avoid unnecessary columns generated in the intermediate projection step

**Comment by duongcongtoai** [comment] 2024-07-15 20:29
https://github.com/apache/datafusion/blob/58f79e143e1a90e5caa59eecc9b36dbdd082a7eb/datafusion/sql/src/select.rs#L344
At this line, before create new projection nodes, we can deduplicate intermediate unnest expr within inner_projection_exprs

**Comment by duongcongtoai** [comment] 2024-07-16 19:08
take

**Comment by duongcongtoai** [comment] 2024-07-16 19:08
also different error types for the following queries:
```
select unnest(column1) + unnest(column1) from unnest_table;
External error: query failed: DataFusion error: Schema error: No field named unnest_table.column1. Valid fields are "unnest(unnest_table.column1)".
```

**Comment by jayzhan211** [comment] 2024-08-09 01:13
I think we can change expr from Debug to Display together with this issue together. This todo is added in #11797
```rust
Expr::Unnest(Unnest { expr }) => {
    // TODO: use Display instead of Debug, there is non-unique expression name in projection issue.
    write!(f, "UNNEST({expr})")
}
```

**Closed** 2024-09-25 10:27 UTC
Labels: bug
