### ISSUE TITLE
Add graphviz format for explain result.

### ISSUE THREAD

**Issue by liurenjie1024** [apache/datafusion#6408] opened 2023-05-22 11:26 UTC
### Is your feature request related to a problem or challenge?

Currently, datafusion only shows explain results in text format, but it's still difficult to read for complex plan. We can show it in graphviz format and display it [here](https://viz-js.com/) to make it easier to read. This is inspired by trinodb: https://trino.io/docs/current/sql/explain.html#explain-type-logical-format-json

**Comment by alamb** [comment] 2023-05-23 11:13
This looks similar / a dupe of to https://github.com/apache/arrow-datafusion/issues/3606

Also possibly related https://github.com/apache/arrow-datafusion/issues/6137

**Closed as completed** 2023-05-25 06:16 UTC
Labels: enhancement
