### ISSUE TITLE
invalid character_octat_length in information schema for tables created with values list

### ISSUE THREAD

**Issue by jimexist** [apache/datafusion#1271] opened 2021-11-08 10:19 UTC
**Describe the bug**

for a table created with create table as values lists, the resulting information schema show invalid `character_octat_length` info

**To Reproduce**

```
❯ create table users as values ('a', 'b');
0 rows in set. Query took 0.002 seconds.
❯ \d
+---------------+--------------------+------------+------------+
| table_catalog | table_schema       | table_name | table_type |
+---------------+--------------------+------------+------------+
| datafusion    | public             | users      | BASE TABLE |
| datafusion    | information_schema | tables     | VIEW       |
| datafusion    | information_schema | columns    | VIEW       |
+---------------+--------------------+------------+------------+
3 rows in set. Query took 0.005 seconds.
❯ select * from information_schema.columns;
+---------------+--------------+------------+-------------+------------------+----------------+-------------+-----------+--------------------------+------------------------+-------------------+-------------------------+---------------+--------------------+---------------+
| table_catalog | table_schema | table_name | column_name | ordinal_position | column_default | is_nullable | data_type | character_maximum_length | character_octet_length | numeric_precision | numeric_precision_radix | numeric_scale | datetime_precision | interval_type |
+---------------+--------------+------------+-------------+------------------+----------------+-------------+-----------+--------------------------+------------------------+-------------------+-------------------------+---------------+--------------------+---------------+
| datafusion    | public       | users      | column1     | 0                |                | YES         | Utf8      |                          | 2147483647             |                   |                         |               |                    |               |
| datafusion    | public       | users      | column2     | 1                |                | YES         | Utf8      |                          | 2147483647             |                   |                         |               |                    |               |
+---------------+--------------+------------+-------------+------------------+----------------+-------------+-----------+--------------------------+------------------------+-------------------+-------------------------+---------------+--------------------+---------------+
2 rows in set. Query took 0.005 seconds.
```

**Expected behavior**

**Additional context**

**Comment by Jimexist** [comment] 2021-11-08 10:22
or maybe not, it's just the field name is confusing...

**Comment by alamb** [comment] 2021-11-08 21:06
I think the `character_octet_length` is supposed to be how to express the `200` for types `VARCHAR(200)` 

Since Arrow doesn't really have the notion of "maximum string length" (other than 2^32 for `Utf8`and 2^64 for `LargeUtf8` I think the number is just hard coded

Or as you (much more) succinctly put it: ", it's just the field name is confusing..."

**Comment by drauschenbach** [comment] 2024-11-01 22:43
This can be closed as it was not a bug.

**Closed** 2024-11-02 20:11 UTC
Labels: bug
