### ISSUE TITLE
cannot find function `bitwise_bin_op_simd_helper` in this scope

### ISSUE THREAD

**Issue by artorias1024** [apache/datafusion#604] opened 2021-06-23 02:42 UTC
**Describe the bug**
When I running the DataFusion Benchmarks and enable eatures `simd`
```
artorias@artorias-ThinkPad-X1-Carbon-Gen-8:~/workspace-vscode/arrow-datafusion/benchmarks$ cargo run --release --features "simd mimalloc" --bin tpch -- benchmark datafusion --iterations 3 --path ./data --format tbl --query 1 --batch-size 4096
   Compiling arrow v4.3.0
error[E0425]: cannot find function `bitwise_bin_op_simd_helper` in this scope
   --> /home/artorias/.cargo/registry/src/github.com-1ecc6299db9ec823/arrow-4.3.0/src/buffer/ops.rs:258:9
    |
125 | / pub fn bitwise_bin_op_helper<F>(
126 | |     left: &Buffer,
127 | |     left_offset_in_bits: usize,
128 | |     right: &Buffer,
...   |
152 | |     buffer.into()
153 | | }
    | |_- similarly named function `bitwise_bin_op_helper` defined here
...
258 |           bitwise_bin_op_simd_helper(
    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^ help: a function with a similar name exists: `bitwise_bin_op_helper`

error[E0425]: cannot find function `bitwise_bin_op_simd_helper` in this scope
   --> /home/artorias/.cargo/registry/src/github.com-1ecc6299db9ec823/arrow-4.3.0/src/buffer/ops.rs:369:9

```

**Comment by pkit** [comment] 2021-07-01 13:06
looks like a duplicate of https://github.com/apache/arrow-rs/issues/232

**Comment by artorias1024** [comment] 2021-07-05 03:43
> looks like a duplicate of [apache/arrow-rs#232](https://github.com/apache/arrow-rs/issues/232)
It does seem to be the same problem, which has been bothering me for a long time  : (

**Comment by drauschenbach** [comment] 2024-11-01 22:32
Obsolete now that there is no `simd` feature.

**Comment by alamb** [comment] 2024-11-02 20:11
Agreed -- the simd feature was removed from arrow a while ago

**Closed by alamb** 2024-11-02 20:11 UTC
Labels: bug
