### ISSUE TITLE
Ensure links in the docs are correct

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#1741] opened 2022-02-03 19:14 UTC
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
There are several broken links in the datafusion crate docs. For example

![Screen Shot 2022-02-03 at 3 09 30 PM](https://user-images.githubusercontent.com/490673/152420969-b1cdd704-200e-47f6-af4d-ce614fd99495.png)

**Describe the solution you'd like**
I would like them all links to be valid and ideally have a CI check to ensure they remain that way 

**Additional context**

See similar ticket in arrow-rs: https://github.com/apache/arrow-rs/issues/1267

**Comment by HaoYang670** [comment] 2022-02-09 07:45
I con work on it if no one else has been doing!

**Comment by HaoYang670** [comment] 2022-02-11 01:16
https://github.com/apache/arrow-datafusion/blob/master/datafusion/src/physical_plan/sorts/sort_preserving_merge.rs#L260

I got 
```
the struct `SortPreservingMergeStream` has no field or associated item named `receivers`
```
when run `cargo doc`.
I am not sure what this link should be.

**Comment by Jefffrey** [comment] 2024-04-21 03:24
Duplicate of #6042

**Closed by Jefffrey** 2024-04-21 03:24 UTC
Labels: enhancement
